version: "3.9"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      
volumes:
  mongo-data: