version: "3.9"
services:
  flask:
    image: python-flask
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./:/usr/src/app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      
volumes:
  mongo-data: