version: "3.9"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    environment:
      - FLASK_DEBUG=true
    volumes:
      - './:/src'
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./volume-mongo:/data/db
      
volumes:
  mongo-data: